export const authGetter = state => state.user
export const usersGetter = state => state.users
export const rolesGetter = state => state.roles
export const tokenGetter = state => state.token
export const locationGetter = state => state.location
export const distanceGetter = state => state.distance
export const rateGetter = state => state.rate
export const currenciesGetter = state => state.currencies
export const currencyGetter = state => state.currency
export const analyticsGetter = state => state.analytics
